# Generated by Django 4.1 on 2022-09-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_activation', '0002_activation_rel_alter_activation_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activation',
            name='rel',
        ),
        migrations.AddField(
            model_name='activation',
            name='uid',
            field=models.IntegerField(default=1),
        ),
    ]
